### PR TITLE
Add msgpack

### PR DESCRIPTION
**Pull request by Seggan**
Added msgpack to both JVM and JS targets (someone would really write a pure Kotlin msgpack impl). Also added the opcode code.

### CODE REVIEW

**Comment by Seggan** [comment]
aaaaaaaaaa git what are you doing

**Comment by Seggan** [comment]
Therrre ya go

**Review by ysthakur — APPROVED** [review]
Rubber-stamping this

**Review by bbrk24 — APPROVED** [review]
LGTM

**Comment by ysthakur** [comment]
kotlin-js-store/yarn.lock needs to be set as generated in .gitattributes. We should also use a formatter, but that's for later.

**Comment by bbrk24** [comment]
> kotlin-js-store/yarn.lock needs to be set as generated in .gitattributes. 

Does GitHub not mark yarn.lock as generated by default?

> We should also use a formatter, but that's for later.

Agreed.

**Pull request merged**
